# Generated by Django 4.2.16 on 2026-07-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_upload',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
