# Generated by Django 5.0.6 on 2026-07-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token_created',
        ),
    ]
