# Generated by Django 4.2.16 on 2026-07-05 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('register', 'User Registered'), ('login', 'User Logged In'), ('logout', 'User Logged Out'), ('email_verified', 'Email Verified'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Updated'), ('place_added', 'Place Added'), ('place_verified', 'Place Verified'), ('place_updated', 'Place Updated'), ('place_deleted', 'Place Deleted'), ('suggestion_submitted', 'Suggestion Submitted'), ('suggestion_processed', 'Suggestion Processed'), ('review_added', 'Review Added'), ('trip_planned', 'Trip Planned'), ('budget_calculated', 'Budget Calculated'), ('wishlist_added', 'Wishlist Added')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action_type', 'created_at'], name='activity_lo_user_id_71c3c2_idx')],
            },
        ),
    ]
