# Generated by Django 5.0.6 on 2026-07-09 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Staff who verified this guide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidereview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guide',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='guide',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Specialties/categories this guide offers', related_name='guides', to='guides.guidecategory'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='districts',
            field=models.ManyToManyField(blank=True, help_text='All districts this guide serves', related_name='guides', to='guides.district'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='languages',
            field=models.CharField(blank=True, default='', help_text='Comma separated languages (e.g., English, Malayalam, Tamil)', max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='guidebooking',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guides.guideavailability'),
        ),
        migrations.AlterField(
            model_name='guidebooking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guides.guidecategory'),
        ),
        migrations.AlterField(
            model_name='guidebooking',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_bookings', to='guides.district'),
        ),
        migrations.AlterField(
            model_name='guidebooking',
            name='special_requests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='guidereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
