# Generated by Django 5.0.6 on 2026-07-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_guide_verified_by_guidereview_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebooking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
