# Generated by Django 4.2.16 on 2026-07-24 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guides', '0003_guidebooking_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='guides', to='guides.guidecategory'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='guides', to='guides.district'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guide',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guide',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guide',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='guide',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guideavailability',
            name='current_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guideavailability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guideavailability',
            name='max_bookings',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='GuideReview',
        ),
    ]
