# Generated by Django 4.2.16 on 2026-07-28 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_destination_last_synced_at_destination_vector_synced_and_more'),
        ('guides', '0004_alter_guide_categories_alter_guide_districts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebooking',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='The destination/location for this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_bookings', to='destinations.destination'),
        ),
    ]
