# Generated by Django 4.2.16 on 2026-07-15 04:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0002_categorydata_categoryplace'),
        ('guides', '0002_guide_verified_by_guidereview_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('new', 'Suggest New Destination'), ('update', 'Update Existing Destination'), ('report', 'Report Issue/Problem'), ('feature', 'Feature Request'), ('hidden_gem', 'Hidden Gem'), ('local_insight', 'Local Insight'), ('review', 'Review')], db_index=True, default='new', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('approved_by_guide', 'Approved by Guide'), ('rejected_by_guide', 'Rejected by Guide'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], db_index=True, default='pending', max_length=20)),
                ('name', models.CharField(default='Unknown Place', max_length=200, validators=[django.core.validators.MinLengthValidator(2, message='Name must be at least 2 characters'), django.core.validators.MaxLengthValidator(200, message='Name cannot exceed 200 characters')])),
                ('title', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200, message='Title cannot exceed 200 characters')])),
                ('description', models.TextField(default='No description provided', max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000, message='Description cannot exceed 5000 characters')])),
                ('category', models.CharField(blank=True, db_index=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50, message='Category cannot exceed 50 characters')])),
                ('location_info', models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MaxLengthValidator(1000, message='Location info cannot exceed 1000 characters')])),
                ('district', models.CharField(db_index=True, default='Unknown', max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='District must be at least 2 characters'), django.core.validators.MaxLengthValidator(100, message='District cannot exceed 100 characters')])),
                ('admin_notes', models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MaxLengthValidator(2000, message='Admin notes cannot exceed 2000 characters')])),
                ('guide_notes', models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MaxLengthValidator(1000, message='Guide notes cannot exceed 1000 characters')])),
                ('rejection_reason', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500, message='Rejection reason cannot exceed 500 characters')])),
                ('image', models.ImageField(blank=True, help_text='Upload an image for your suggestion (max 5MB)', max_length=500, null=True, upload_to='suggestions/%Y/%m/%d/')),
                ('images', models.JSONField(blank=True, default=list, help_text='Additional images as URLs or paths')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1'), django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5')])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional JSON data')),
                ('visit_date', models.DateField(blank=True, help_text='When did you visit this place?', null=True)),
                ('guide_processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, db_column='destination_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='destinations.destination')),
                ('guide', models.ForeignKey(blank=True, db_column='guide_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='guides.guide')),
                ('processed_by', models.ForeignKey(blank=True, db_column='processed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'suggestion_type'], name='suggestions_user_id_215724_idx'), models.Index(fields=['district', 'status'], name='suggestions_distric_6bb5f6_idx'), models.Index(fields=['status', 'created_at'], name='suggestions_status_1ac4ed_idx'), models.Index(fields=['category', 'status'], name='suggestions_categor_c2e15e_idx'), models.Index(fields=['guide', 'status'], name='suggestions_guide_i_b110d2_idx')],
            },
        ),
    ]
