# Generated by Django 4.2.16 on 2026-07-31 12:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0007_alter_categoryplace_district'),
        ('guides', '0005_guidebooking_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_approved_at', models.DateTimeField(blank=True, null=True)),
                ('guide_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('staff_approved_at', models.DateTimeField(blank=True, null=True)),
                ('staff_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('admin_implemented_at', models.DateTimeField(blank=True, null=True)),
                ('suggestion_type', models.CharField(choices=[('hidden_gem', 'Hidden Gem'), ('local_insight', 'Local Insight'), ('review', 'Review'), ('new', 'Suggest New Destination'), ('update', 'Update Existing Destination'), ('feature', 'Feature Request')], db_index=True, default='hidden_gem', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('pending_guide', 'Pending Guide Approval'), ('pending_admin', 'Pending Admin Approval'), ('approved_by_guide', 'Approved by Guide'), ('rejected_by_guide', 'Rejected by Guide'), ('staff_approved', 'Approved by Staff'), ('staff_rejected', 'Rejected by Staff'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], db_index=True, default='pending', max_length=20)),
                ('name', models.CharField(default='Untitled', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('title', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('description', models.TextField(default='No description provided', max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('category', models.CharField(blank=True, db_index=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('location_info', models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('district', models.CharField(db_index=True, default='Unknown', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('admin_notes', models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('guide_notes', models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('rejection_reason', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('guide_processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_implemented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_implemented_suggestions', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='destinations.destination')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='guides.guide')),
                ('guide_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_approved_suggestions', to=settings.AUTH_USER_MODEL)),
                ('guide_rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_rejected_suggestions', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('staff_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_approved_suggestions', to=settings.AUTH_USER_MODEL)),
                ('staff_rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_rejected_suggestions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('suggestion_created', 'New Suggestion Created'), ('suggestion_approved', 'Suggestion Approved'), ('suggestion_rejected', 'Suggestion Rejected'), ('suggestion_implemented', 'Suggestion Implemented'), ('guide_review', 'Guide Review Required'), ('staff_review', 'Staff Review Required'), ('admin_action', 'Admin Action Required')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('message', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='suggestions.suggestion')),
            ],
            options={
                'db_table': 'suggestion_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='suggestion__recipie_fb723b_idx'), models.Index(fields=['recipient', 'created_at'], name='suggestion__recipie_d6e1d1_idx'), models.Index(fields=['suggestion'], name='suggestion__suggest_0d165f_idx'), models.Index(fields=['notification_type'], name='suggestion__notific_3943dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuggestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='suggestions/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='suggestions.suggestion')),
            ],
            options={
                'db_table': 'suggestion_images',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['suggestion'], name='suggestion__suggest_34d2fa_idx'), models.Index(fields=['suggestion', 'is_primary'], name='suggestion__suggest_6cd21b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['user', 'status', 'suggestion_type'], name='suggestions_user_id_215724_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['district', 'status'], name='suggestions_distric_6bb5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['status', 'created_at'], name='suggestions_status_1ac4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['category', 'status'], name='suggestions_categor_c2e15e_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['guide', 'status'], name='suggestions_guide_i_b110d2_idx'),
        ),
    ]
