# Generated by Django 5.0.6 on 2026-07-16 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='district',
            field=models.CharField(db_index=True, default='Unknown', max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='District cannot exceed 100 characters')]),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='name',
            field=models.CharField(default='Unknown Place', max_length=200, validators=[django.core.validators.MaxLengthValidator(200, message='Name cannot exceed 200 characters')]),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5')]),
        ),
    ]
