# Generated by Django 5.0.6 on 2026-07-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_categoryplace_created_by_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryplace',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_places', to='destinations.destination'),
        ),
    ]
