# Generated by Django 5.0.6 on 2026-07-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_categoryplace_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryplace',
            name='district',
            field=models.CharField(blank=True, help_text='District where this place is located', max_length=100, null=True),
        ),
    ]
