# Generated by Django 4.2.16 on 2026-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_categoryplace_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this destination was synced to Qdrant', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='vector_synced',
            field=models.BooleanField(default=False, help_text='Whether this destination is indexed in Qdrant'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['vector_synced'], name='destination_vector__5fadb7_idx'),
        ),
    ]
