# Generated by Django 4.2.16 on 2026-07-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_destination_last_synced_at_destination_vector_synced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryplace',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
