# Generated by Django 4.2.16 on 2026-07-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnotification',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
